.TH zbectl 8 "June 06, 2017" "version 1.0"
.SH NAME
zbectl - Control ZFS Boot Environments
.SH SYNOPSIS
\fBzbectl list\fB

\fBzbectl create\fB \fR[\fIsource\fR] \fItarget\fI

\fBzbectl rename\fB \fIsource target\fI

\fBzbectl destroy\fB \fItarget...\fI

\fBzbectl activate\fB

\fBzbectl activate\fB \fItarget\fI

\fBzbectl update\fB

\fBzbectl install\fB \fI[grub arguments]\fI

.SH DESCRIPTION

\fBzbectl\fR is a utility for managing \fIZFS Boot Environments\fR in Arch Linux.

Boot entries for \fBgrub \fR are also created automatically.

The script assumes that your Boot Environments are located under \fIpoolname/ROOT/\fR and that your efi partition is mounted under \fI/boot/efi\fR.

.SS SUBCOMMANDS
.TP
.B zbectl list
Lists all 
.I ZFS Boot Environments.
.TP
\fBzbectl create\fB \fR[\fIsource\fR] \fItarget\fI
Creates a new ZFS Boot Environment named \fItarget\fR. If no \fIsource\fR environment is provided, the \fIbooted\fR environment will be used.
.TP
\fBzbectl rename\fB \fIsource target\fI
Renames the \fIsource\fR environment to \fItarget\fR.
.TP
\fBzbectl destroy\fB \fItarget...\fI
Delets the \fItarget\fR environment(s).
.TP
\fBzbectl activate\fB
Lists available environments.
.TP
\fBzbectl activate\fB \fItarget\fI
Sets the \fItarget\fR as the default boot entry. Note that the entire name is not requirred, as long as the script can figure out which environment is ment.
.TP
\fBzbectl update\fB
Updates \fIgrub.cfg\fR.
.TP
\fBzbectl install\fB \fR[\fIgrub arguments\fR]
Installs grub to efi partition and updates \fIgrub.cfg\fR. Additional arguments are passed to \fBgrub-install\fR.

.SH EXIT CODES
The following exit codes are returned:
.TP
\fB0
Successful execution.
.TP
\fB1
An error occurred.

.SH AUTHOR

Nicolai <Finic8@protonmail.com>

Source at <https://github.com/Finic8/zbectl>

.SH SEE ALSO
\fBbootctl\fR(1), \fBzfs\fR(8)\fR
